# Generated by Django 6.0.7 on 2026-09-10 05:42

import chat.models
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_tbl_booking_proposal'),
        ('chat', '0004_tbl_chat_message_message_payload_not_empty_or_whitespace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat_reaction',
            fields=[
                ('reaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=10)),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_chat_reaction',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tbl_chat_message',
            name='message_payload_not_empty_or_whitespace',
        ),
        migrations.AddField(
            model_name='tbl_chat_message',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tbl_chat_message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_chat_message',
            name='message_payload',
            field=chat.models.EncryptedTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='tbl_chat_message',
            constraint=models.CheckConstraint(condition=models.Q(('message_type', 'image'), django.db.models.expressions.RawSQL('length(trim(message_payload)) > 0', [], output_field=models.BooleanField()), _connector='OR'), name='message_payload_not_empty_or_whitespace'),
        ),
        migrations.AddConstraint(
            model_name='tbl_chat_message',
            constraint=models.CheckConstraint(condition=models.Q(('message_type', 'image'), ('image_public_id__isnull', True), _connector='OR'), name='text_message_cannot_have_image_public_id'),
        ),
        migrations.AddField(
            model_name='tbl_chat_reaction',
            name='message',
            field=models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.tbl_chat_message'),
        ),
        migrations.AddField(
            model_name='tbl_chat_reaction',
            name='reactor',
            field=models.ForeignKey(db_column='reactor_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tbl_chat_reaction',
            constraint=models.UniqueConstraint(fields=('message', 'reactor'), name='one_reaction_per_user_per_message'),
        ),
    ]
