# Generated by Django 6.0.7 on 2026-08-06 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tbl_user_profile_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user_profile',
            name='contact_number',
            field=models.CharField(default='+630000000000', help_text="User's contact phone number (e.g. +639123456789)", max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+63' followed by 10 digits (e.g., +639123456789).", regex='^\\+63\\d{10}$')]),
            preserve_default=False,
        ),
    ]
