# Generated by Django 6.0.7 on 2026-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tbl_user_profile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='profile_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
