# Generated by Django 6.0.7 on 2026-08-15 08:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tbl_user_profile_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='user_about',
            field=models.TextField(blank=True, default='No Bio', max_length=500),
        ),
        migrations.AddField(
            model_name='tbl_user_profile',
            name='user_tags',
            field=models.JSONField(blank=True, default=list, validators=[accounts.models.validate_user_tags]),
        ),
    ]
