# Generated by Django 6.0.7 on 2026-08-15 08:35

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tbl_user_profile_user_about_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbl_user_profile',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL("jsonb_typeof(user_tags) = 'array'", [], output_field=models.BooleanField()), name='valid_user_tags_must_be_array'),
        ),
    ]
