# Generated by Django 6.0.7 on 2026-08-15 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tbl_user_profile_valid_user_tags_must_be_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user_profile',
            name='contact_number',
            field=models.CharField(help_text="User's contact phone number (e.g. +639123456789)", max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+63' followed by 10 digits (e.g., +639123456789).", regex='^\\+639\\d{9}$')]),
        ),
    ]
