# Generated by Django 6.0.7 on 2026-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_tbl_user_profile_valid_verification_status_enum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='show_contact_number',
            field=models.BooleanField(default=False, help_text='Controls if contact number is visible to other users on public profile'),
        ),
    ]
