# Generated by Django 6.0.7 on 2026-09-10 03:51

import accounts.models
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tbl_user_profile_show_contact_number'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='show_social_links',
            field=models.BooleanField(default=True, help_text='Controls if social links are visible to other users on public profile'),
        ),
        migrations.AddField(
            model_name='tbl_user_profile',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text="User's external social contact links (Facebook, Instagram, Telegram, etc.)", validators=[accounts.models.validate_social_links]),
        ),
        migrations.AddConstraint(
            model_name='tbl_user_profile',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL("jsonb_typeof(social_links) = 'array'", [], output_field=models.BooleanField()), name='valid_social_links_must_be_array'),
        ),
    ]
