# Generated by Django 6.0.7 on 2026-09-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tbl_user_profile_show_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='is_on_job',
            field=models.BooleanField(default=False, help_text='Kasambahay employment status: True if On the Job, False if Available'),
        ),
    ]
