# Generated by Django 6.0.7 on 2026-09-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_social_links'),
        ('accounts', '0011_tbl_user_profile_is_on_job'),
    ]

    operations = [
    ]
