# Generated by Django 6.0.7 on 2026-09-11 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260911_2016'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user_profile',
            name='contact_number',
            field=models.CharField(help_text="User's unique contact phone number (e.g. +639123456789)", max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+63' followed by 10 digits (e.g., +639123456789).", regex='^\\+639\\d{9}$')]),
        ),
        migrations.AddConstraint(
            model_name='tbl_user_profile',
            constraint=models.UniqueConstraint(fields=('contact_number',), name='unique_tbl_user_profile_contact_number'),
        ),
        migrations.AddConstraint(
            model_name='tbl_user_profile',
            constraint=models.CheckConstraint(condition=models.Q(('contact_number__regex', '^\\+639\\d{9}$')), name='valid_contact_number_e164_format'),
        ),
    ]
