# Generated by Django 6.0.7 on 2026-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_tbl_user_profile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='barangay',
            field=models.CharField(blank=True, help_text='Barangay name within the city/municipality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_user_profile',
            name='region',
            field=models.CharField(blank=True, help_text='Philippine region (e.g. Region X - Northern Mindanao)', max_length=100, null=True),
        ),
    ]
