# Generated by Django 6.0.7 on 2026-10-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_region_barangay_to_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_user_profile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='tbl_user_profile',
            name='street',
            field=models.CharField(blank=True, help_text='House/Lot/Block number, street name, zone, or subdivision only. NOT the barangay.', max_length=100, null=True),
        ),
    ]
