# Generated by Django 6.0.7 on 2026-10-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_drop_physical_verification_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbl_user_profile',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'Barangay'), models.Q(('barangay__isnull', True), _negated=True), models.Q(('barangay', ''), _negated=True)), fields=('barangay',), name='unique_lgu_account_per_barangay'),
        ),
    ]
