# Generated by Django 6.0.7 on 2026-08-03 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], max_length=20)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('service_category', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('service_address', models.CharField(max_length=255)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_booking',
                'constraints': [models.CheckConstraint(condition=models.Q(('booking_type__in', ['short_term', 'long_term'])), name='valid_booking_type_enum'), models.CheckConstraint(condition=models.Q(('booking_status__in', ['Pending', 'Accepted', 'InProgress', 'Completed', 'Cancelled'])), name='valid_booking_status_enum')],
            },
        ),
    ]
