# Generated by Django 6.0.7 on 2026-08-03 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='poster_id',
            field=models.ForeignKey(limit_choices_to={'account_type__in': ['Homeowner', 'Kasambahay']}, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
