# Generated by Django 6.0.7 on 2026-08-03 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_tbl_booking_poster_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking_assignment',
            fields=[
                ('booking_assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepter_id', models.ForeignKey(db_column='accepter_id', limit_choices_to={'account_type': 'Kasambahay'}, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_bookings', to=settings.AUTH_USER_MODEL)),
                ('booking_id', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='booking.tbl_booking')),
            ],
            options={
                'db_table': 'tbl_booking_assignment',
            },
        ),
    ]
