# Generated by Django 6.0.7 on 2026-08-05 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_tbl_booking_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking_assignment',
            name='accepter_id',
            field=models.ForeignKey(db_column='accepter_id', limit_choices_to={'account_type__in': ['Homeowner', 'Kasambahay']}, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
