# Generated by Django 6.0.7 on 2026-08-08 07:51

import django.contrib.postgres.fields
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_tbl_booking_assignment_accepter_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='floor_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='zip_code',
            field=models.CharField(default=6000, max_length=4, validators=[django.core.validators.RegexValidator('^(0[4-9]\\d{2}|[1-9]\\d{3})$', 'Zip code must be exactly 4 digits')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='service_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Cleaning', 'Cleaning'), ('Child_care', 'Child Care'), ('Cooking', 'Cooking'), ('Caregiver', 'Caregiver'), ('Laundry', 'Laundry'), ('All-around', 'All around')], max_length=50)),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='special_instruction',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddConstraint(
            model_name='tbl_booking',
            constraint=models.CheckConstraint(condition=models.Q(('service_category__contained_by', ['Cleaning', 'Child_care', 'Cooking', 'Caregiver', 'Laundry', 'All-around'])), name='validate_service_category_array'),
        ),
        migrations.AddConstraint(
            model_name='tbl_booking',
            constraint=models.CheckConstraint(condition=models.Q(('service_category__len__gt', 0)), name='service_category_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tbl_booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', True), _connector='OR'), name='end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='tbl_booking',
            constraint=models.CheckConstraint(condition=models.Q(('daily_rate__gte', Decimal('1.00'))), name='valid_daily_rate'),
        ),
    ]
