# Generated by Django 6.0.7 on 2026-08-08 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_tbl_booking_daily_rate_tbl_booking_floor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='zip_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^(0[4-9]\\d{2}|[1-9]\\d{3})$', 'Must be a valid 4-digit Philippine Zip Code (0400 or higher).')]),
        ),
    ]
