# Generated by Django 6.0.7 on 2026-09-05 17:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tbl_booking_zip_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking_proposal',
            fields=[
                ('proposal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='booking.tbl_booking')),
                ('proposer_id', models.ForeignKey(db_column='proposer_id', limit_choices_to={'account_type__in': ['Homeowner', 'Kasambahay']}, on_delete=django.db.models.deletion.CASCADE, related_name='booking_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_booking_proposal',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['Pending', 'Accepted', 'Rejected', 'Withdrawn'])), name='valid_proposal_status_enum'), models.CheckConstraint(condition=models.Q(('proposed_rate__gte', Decimal('1.00'))), name='valid_proposal_rate')],
            },
        ),
    ]
