# Generated by Django 6.0.7 on 2026-09-14 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_tbl_booking_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='barangay',
            field=models.CharField(blank=True, help_text='Barangay name within city/municipality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='region',
            field=models.CharField(blank=True, help_text='Philippine region (e.g. Region X - Northern Mindanao)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='street',
            field=models.CharField(blank=True, help_text='House No. / Street / Zone / Subdivision', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='service_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='zip_code',
            field=models.CharField(blank=True, default='9000', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^(0[4-9]\\d{2}|[1-9]\\d{3})$', 'Must be a valid 4-digit Philippine Zip Code (0400 or higher).')]),
        ),
    ]
