# Generated by Django 6.0.7 on 2026-09-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_tbl_booking_barangay_tbl_booking_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='service_address',
        ),
    ]
