# Generated by Django 6.0.7 on 2026-08-03 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_tbl_booking_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unstructured_feedback', models.TextField(blank=True, null=True)),
                ('nlp_sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('review_direction', models.CharField(max_length=30)),
                ('booking_id', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.tbl_booking')),
                ('reviewee_id', models.ForeignKey(db_column='reviewee_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer_id', models.ForeignKey(db_column='reviewer_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_review',
                'constraints': [models.CheckConstraint(condition=models.Q(('nlp_sentiment__in', ['Positive', 'Negative', 'Neutral'])), name='valid_nlp_sentiment_enum'), models.CheckConstraint(condition=models.Q(('review_direction__in', ['EmployerToWorker', 'WorkerToEmployer'])), name='valid_review_direction_enum')],
            },
        ),
    ]
