# Generated by Django 6.0.7 on 2026-08-02 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_documents',
            name='verification_status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='verifyBy',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['Admin', 'Barangay']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbl_documents',
            name='document_type',
            field=models.CharField(choices=[('nbi_clearance', 'NBI Clearance'), ('police_clearance', 'Police Clearance'), ('national_id_front', 'National ID (Front)'), ('national_id_back', 'National ID (Back)')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tbl_documents',
            constraint=models.CheckConstraint(condition=models.Q(('document_type__in', ['nbi_clearance', 'police_clearance', 'national_id_front', 'national_id_back'])), name='valid_document_type_enum'),
        ),
        migrations.AddConstraint(
            model_name='tbl_documents',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status__in', ['Unverified', 'Pending', 'Verified', 'Rejected'])), name='valid_document_verification_status_enum'),
        ),
    ]
