# Generated by Django 6.0.7 on 2026-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_tbl_documents_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_documents',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_documents',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='tbl_documents',
            table='tbl_documents',
        ),
    ]
