# Generated by Django 6.0.7 on 2026-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0003_alter_tbl_documents_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_documents',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='face_liveness_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
