# Generated by Django 6.0.7 on 2026-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0003_alter_tbl_documents_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_documents',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='face_liveness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_discrepancies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_documents',
            name='verification_status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
