# Generated by Django 6.0.7 on 2026-09-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0004_tbl_documents_extracted_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times OCR processing has been retried'),
        ),
    ]
