# Generated by Django 6.0.7 on 2026-09-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0004_tbl_documents_document_number_and_more'),
        ('verifications', '0005_tbl_documents_ocr_retry_count'),
    ]

    operations = [
    ]
