# Generated by Django 6.0.7 on 2026-09-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0006_merge_20260910_1153'),
        ('verifications', '0006_merge_20260910_1342'),
    ]

    operations = [
    ]
