# Generated by Django 6.0.7 on 2026-09-14 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0007_merge_20260911_2016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_documents',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured data extracted by Groq AI from OCR text', null=True),
        ),
        migrations.CreateModel(
            name='tbl_audit_logs',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_email', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('actor_barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_email', models.CharField(blank=True, max_length=255, null=True)),
                ('target_role', models.CharField(blank=True, max_length=50, null=True)),
                ('target_barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('document_id_snapshot', models.UUIDField(blank=True, help_text='Preserved document UUID', null=True)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESET', 'Reset to Pending'), ('DELETED', 'Deleted'), ('UPLOADED', 'Uploaded'), ('REPROCESSED', 'Reprocessed'), ('UPDATED', 'Updated')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, help_text='Rejection reason or action remarks', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='verifications.tbl_documents')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='tbl_audit_l_created_a3a87b_idx'), models.Index(fields=['action'], name='tbl_audit_l_action_af49c0_idx'), models.Index(fields=['actor_role'], name='tbl_audit_l_actor_r_aa346b_idx'), models.Index(fields=['target_barangay'], name='tbl_audit_l_target__ebb4fe_idx')],
            },
        ),
    ]
