# Generated by Django 6.0.7 on 2026-08-03 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_message', models.TextField()),
                ('notification_state', models.CharField(default='Unread', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_notification',
                'constraints': [models.CheckConstraint(condition=models.Q(('notification_state__in', ['Read', 'Unread'])), name='valid_notification_state_enum')],
            },
        ),
    ]
